language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
env:
  - DJANGO=Django==1.7.10
  - DJANGO=Django==1.8.6
  - DJANGO=https://www.djangoproject.com/download/1.9b1/tarball/
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test django_file_form_example
  - coverage run --source=django_file_form,testproject/django_file_form_example testproject/manage.py test django_file_form_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: pypy
      env: DJANGO=Django==1.8.6
    - python: pypy
      env: DJANGO=https://www.djangoproject.com/download/1.9b1/tarball/
    - python: 3.5
      env: DJANGO=Django==1.7.10
