language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.3
  - DJANGO=https://www.djangoproject.com/download/1.7b2/tarball/
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - python setup.py install
script:
  - cd testproject
  - python manage.py test django_file_form_example
  - coverage run --source=django_file_form,django_file_form_example manage.py test django_file_form_example
  - coverage report
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
after_success:
  - coveralls
  - cd ..
  - covio
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.7b2/tarball/
    - python: 3.3
      env: DJANGO=Django==1.4.10
