language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=Django==1.4.19
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.10
  - DJANGO=Django==1.7.6
  - DJANGO=https://www.djangoproject.com/download/1.8b2/tarball/
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test django_file_form_example
  - coverage run --source=django_file_form,testproject/django_file_form_example testproject/manage.py test django_file_form_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.6
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.8b2/tarball/
    - python: 3.3
      env: DJANGO=Django==1.4.19
    - python: 3.4
      env: DJANGO=Django==1.4.19
    - python: pypy
      env: DJANGO=Django==1.4.19
    - python: pypy
      env: DJANGO=Django==1.5.12
    - python: pypy
      env: DJANGO=Django==1.6.10
    - python: pypy
      env: DJANGO=https://www.djangoproject.com/download/1.8b2/tarball/
