language: python
dist: bionic
addons:
  chrome: stable
services:
  - postgresql
matrix:
  include:
    - python: 3.7
      env: DJANGO="Django==2.2.12"
    - python: 3.8
      env: DJANGO="Django==3.0.6"
    - python: 3.8
      env: DJANGO="Django==3.1a1"
before_install:
  - CHROME_VERSION="$(google-chrome --version)"
  - export CHROMEDRIVER_RELEASE="$(echo $CHROME_VERSION | sed 's/^Google Chrome //')" && export CHROMEDRIVER_RELEASE=${CHROMEDRIVER_RELEASE%%.*}
  - CHROMEDRIVER_VERSION=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROMEDRIVER_RELEASE})
  - curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
  - cd /tmp
  - unzip chromedriver_linux64.zip
  - rm -rf chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python -Wd testproject/manage.py test django_file_form_example -v 2
  - coverage run --source=django_file_form,testproject/django_file_form_example testproject/manage.py test django_file_form_example -v 2
  - coverage report
after_success:
  - coveralls
